# Generated by Django 5.2 on 2025-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="菜单名称"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="菜单URL"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        max_length=255, null=True, verbose_name="菜单图标"
                    ),
                ),
                ("parent_id", models.IntegerField(null=True, verbose_name="父菜单ID")),
                ("order", models.IntegerField(null=True, verbose_name="菜单排序")),
                (
                    "path",
                    models.CharField(
                        max_length=255, null=True, verbose_name="菜单路径"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        max_length=255, null=True, verbose_name="菜单组件"
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        max_length=255, null=True, verbose_name="菜单类型"
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        max_length=255, null=True, verbose_name="权限标识"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role",
                    models.CharField(max_length=255, null=True, verbose_name="角色"),
                ),
            ],
            options={
                "db_table": "menu",
            },
        ),
    ]
