# Generated by Django 5.2 on 2025-05-03 16:28

import django.db.models.deletion
import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("total_chunks", models.IntegerField()),
                ("received_chunks", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="uploading",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=files.models.attachment_upload_to)),
                ("thumbnail", models.ImageField(null=True, upload_to="thumbnails/")),
                ("converted", models.BooleanField(default=False)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.uploadsession",
                    ),
                ),
            ],
        ),
    ]
