# Generated by Django 5.2 on 2025-05-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_file",
        ),
        migrations.AddField(
            model_name="ticket",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, to="files.attachment", verbose_name="关联附件"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_code",
            field=models.CharField(max_length=12, unique=True, verbose_name="工单编号"),
        ),
    ]
